# Voice Sample Metadata
# This file tracks metadata for all samples used in voice calibration.
# Update this file when adding samples to include engagement data.

last_updated: null
last_calibration: null
calibration_count: 0

samples:
  # LinkedIn samples
  # Add entries as you add sample files:
  #
  # - filename: "2024-10-15-ai-agents-adoption.md"
  #   platform: "linkedin"
  #   date: "2024-10-15"
  #   engagement:
  #     likes: 120
  #     comments: 15
  #     shares: 8
  #   topics: ["AI agents", "adoption"]
  #   high_performer: true  # Flag best-performing content

  # Newsletter samples
  # - filename: "2024-12-20-year-review.md"
  #   platform: "newsletter"
  #   date: "2024-12-20"
  #   subject: "2024: The Year AI Got Real"
  #   engagement:
  #     opens: 450
  #     clicks: 89
  #   topics: ["year review", "AI transformation"]
  #   high_performer: true

# Calibration history
calibration_history: []
  # Entries added automatically by /voice-calibrate:
  # - date: "2025-01-15"
  #   samples_analyzed: 12
  #   confidence: "high"
  #   changes_made:
  #     - "Added 3 terms to vocabulary.include_often"
  #     - "Updated 2 opener patterns"
